/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Dominio.Cliente;
import Dominio.Hotel;
import Excepciones.BOException;
import Negocio.HotelBO;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * Formulario para mostrar la lista de hoteles y permitir al usuario seleccionar
 * uno. Luego, se abre el formulario de habitaciones correspondiente al hotel
 * seleccionado.
 *
 * @author YeisiPC
 */
public class frmHotel1 extends javax.swing.JFrame {

    private final HotelBO hotelBO;
    private Cliente clienteRegistrado;

    /**
     * Creates new form frmHotel
     *
     * @param clienteRegistrado Cliente que ha iniciado sesión.
     */
    public frmHotel1(Cliente clienteRegistrado) {

        initComponents();
        this.clienteRegistrado = clienteRegistrado;
        hotelBO = new HotelBO(); // Initialize HotelBO
        cargarDatosEnTabla();
    }

    private frmHotel1() {
        initComponents();
        hotelBO = new HotelBO(); // Initialize HotelBO
        cargarDatosEnTabla();
    }

    /**
     * Método para cargar los datos de los hoteles en la tabla.
     */
    private void cargarDatosEnTabla() {
        try {
            // Llamar al método para obtener todos los hoteles
            List<Hotel> hoteles = hotelBO.obtenerTodosLosHoteles();

            // Crear un DefaultTableModel con nombres de columnas
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("Nombre");
            model.addColumn("Dirección");
            model.addColumn("Teléfono");
            model.addColumn("Año Construcción");
            model.addColumn("Categoría");

            // Añadir datos al modelo de tabla
            for (Hotel hotel : hoteles) {
                Object[] rowData = new Object[]{
                    hotel.getNombre(),
                    hotel.getDireccion(),
                    hotel.getTelefono(),
                    hotel.getAñoConstruccion(),
                    // Comprueba si Categoria es nula antes de acceder a sus métodos
                    hotel.getCategoria() != null ? hotel.getCategoria().getEstrellas() : "N/A"
                };
                model.addRow(rowData);
            }

            // Establecer el modelo de tabla a la jTableHoteles
            tablaHoteles.setModel(model);

        } catch (BOException ex) {
            Logger.getLogger(frmHotel1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaHoteles = new javax.swing.JTable();
        btnSeleccionarHotel = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaHoteles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaHoteles);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 560, 310));

        btnSeleccionarHotel.setContentAreaFilled(false);
        btnSeleccionarHotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarHotelActionPerformed(evt);
            }
        });
        jPanel1.add(btnSeleccionarHotel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 390, 180, 60));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pantallaSeleccionarHotel.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 520));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
 /**
     * Método invocado al hacer clic en el botón "Seleccionar Hotel". Obtiene el
     * hotel seleccionado y abre el formulario de habitaciones.
     *
     * @param evt Evento de acción al hacer clic en el botón "Seleccionar
     * Hotel".
     */
    private void btnSeleccionarHotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarHotelActionPerformed
        // TODO add your handling code here:
        int indiceHotel = tablaHoteles.getSelectedRow();

        if (indiceHotel == -1) {
            // Si no se ha seleccionado ninguna fila, mostrar un mensaje de error
            JOptionPane.showMessageDialog(this, "Por favor, seleccione un hotel.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Continuar con el resto del código
        String nombre = tablaHoteles.getValueAt(indiceHotel, 0).toString();

        try {
            Hotel hotelSeleccionado = hotelBO.buscar(nombre);
            new frmHabitacion1(this.clienteRegistrado, hotelSeleccionado).setVisible(true);
            this.dispose();
        } catch (BOException e) {
            e.printStackTrace(); // Puedes considerar mostrar un mensaje de error adicional aquí
    }//GEN-LAST:event_btnSeleccionarHotelActionPerformed
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmHotel1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmHotel1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmHotel1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmHotel1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmHotel1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSeleccionarHotel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaHoteles;
    // End of variables declaration//GEN-END:variables
}
