/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Dominio.Reservacion;
import Excepciones.BOException;
import Negocio.ReservacionBO;
import javax.swing.JOptionPane;

/**
 *
 * @author YeisiPC
 */
public class frmReporteDeReservacion1 extends javax.swing.JFrame {

    private ReservacionBO reservacionBO;
    private Reservacion reservacion;

    /**
     * Constructor de la clase 'frmReporteDeReservacion1'. Inicializa y muestra
     * los componentes gráficos del formulario.
     *
     * @param reservacion Reservación para la cual se genera el reporte.
     */
    public frmReporteDeReservacion1(Reservacion reservacion) {
        initComponents();
        this.reservacionBO = new ReservacionBO();
        this.reservacion = reservacion;

        String nombreCliente = this.reservacion.getCliente().getNombre();
        Double tarifa = this.reservacion.getTarifa();
        int periodoEstancia = this.reservacion.getPeriodoEstancia();
        String nombreHotel = this.reservacion.getCategoriaHotel().getNombre();
        String tipoHabitacion = this.reservacion.getClaseHabitacion().getTipoHabitacion();
        int categoriaHotel = this.reservacion.getCategoriaHotel().getCategoria().getEstrellas();
        lbNombre.setText(nombreCliente);
        lbTarifa.setText(String.valueOf(tarifa));
        lbPeriodo.setText(String.valueOf(periodoEstancia));
        lbHotel.setText(nombreHotel);
        lbHabitacion.setText(tipoHabitacion);
        lbCategoria.setText(String.valueOf(categoriaHotel));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbNombre = new javax.swing.JLabel();
        lbPeriodo = new javax.swing.JLabel();
        lbHotel = new javax.swing.JLabel();
        lbCategoria = new javax.swing.JLabel();
        lbHabitacion = new javax.swing.JLabel();
        lbTarifa = new javax.swing.JLabel();
        btnRealizarReservacion = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(650, 480));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbNombre.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbNombre.setForeground(new java.awt.Color(0, 0, 0));
        lbNombre.setText("jLabel2");
        jPanel1.add(lbNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 280, -1));

        lbPeriodo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbPeriodo.setForeground(new java.awt.Color(0, 0, 0));
        lbPeriodo.setText("jLabel3");
        jPanel1.add(lbPeriodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 290, -1));

        lbHotel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbHotel.setForeground(new java.awt.Color(0, 0, 0));
        lbHotel.setText("jLabel3");
        jPanel1.add(lbHotel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 290, -1));

        lbCategoria.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbCategoria.setForeground(new java.awt.Color(0, 0, 0));
        lbCategoria.setText("jLabel3");
        jPanel1.add(lbCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 290, -1));

        lbHabitacion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbHabitacion.setForeground(new java.awt.Color(0, 0, 0));
        lbHabitacion.setText("jLabel3");
        jPanel1.add(lbHabitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, 290, -1));

        lbTarifa.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbTarifa.setForeground(new java.awt.Color(0, 0, 0));
        lbTarifa.setText("jLabel3");
        jPanel1.add(lbTarifa, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 290, -1));

        btnRealizarReservacion.setContentAreaFilled(false);
        btnRealizarReservacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRealizarReservacionActionPerformed(evt);
            }
        });
        jPanel1.add(btnRealizarReservacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 393, 150, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pantallaReporteReservacion.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
 /**
     * Maneja el evento de clic en el botón "btnRealizarReservacion". Realiza la
     * inserción de la reservación y muestra un mensaje de éxito.
     *
     * @param evt Evento de acción.
     */
    private void btnRealizarReservacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRealizarReservacionActionPerformed
        // TODO add your handling code here:
        try {
            this.reservacionBO.insertar(this.reservacion);
            JOptionPane.showMessageDialog(null, "Reservación realizada correctamente");
            frmInicial1 ini = new frmInicial1();
            ini.setVisible(true);
            this.dispose();
        } catch (BOException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnRealizarReservacionActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(frmReporteDeReservación.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(frmReporteDeReservación.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(frmReporteDeReservación.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(frmReporteDeReservación.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new frmReporteDeReservación().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRealizarReservacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbCategoria;
    private javax.swing.JLabel lbHabitacion;
    private javax.swing.JLabel lbHotel;
    private javax.swing.JLabel lbNombre;
    private javax.swing.JLabel lbPeriodo;
    private javax.swing.JLabel lbTarifa;
    // End of variables declaration//GEN-END:variables
}
