/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;
import Dominio.AgenciaDeViajes;
import Dominio.Cliente;
import Dominio.Persona;
/**
 *
 * @author YeisiPC
 */
public class frmTipoDeReservación extends javax.swing.JFrame {

    /**
     * Creates new form frmTipoDeReservación
     */
    public frmTipoDeReservación() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEleccionPersonal = new javax.swing.JButton();
        btnEleccionAgencia = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnEleccionPersonal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEleccionPersonal.setIcon(new javax.swing.ImageIcon("C:\\Users\\YeisiPC\\Documents\\GitHub\\ProyectoHotelesMongoDB\\toolbar\\Security_Card.png")); // NOI18N
        btnEleccionPersonal.setText("Personal");
        btnEleccionPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEleccionPersonalActionPerformed(evt);
            }
        });

        btnEleccionAgencia.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEleccionAgencia.setIcon(new javax.swing.ImageIcon("C:\\Users\\YeisiPC\\Documents\\GitHub\\ProyectoHotelesMongoDB\\toolbar\\Globe.png")); // NOI18N
        btnEleccionAgencia.setText("Agencia de viajes");
        btnEleccionAgencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEleccionAgenciaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Elegir medio de reservacion");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(btnEleccionPersonal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(btnEleccionAgencia)
                .addGap(24, 24, 24))
            .addGroup(layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 143, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEleccionPersonal)
                    .addComponent(btnEleccionAgencia))
                .addGap(77, 77, 77))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEleccionPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEleccionPersonalActionPerformed
        // Create an instance of frmHotel
        Cliente cliente = new Persona();
        
        frmPersona personaFrame = new frmPersona(cliente);

        // Make the frmHotel frame visible
        personaFrame.setVisible(true);

        // Close the current frame if needed
        this.dispose(); // Add this line if you want to close the current frame
    }//GEN-LAST:event_btnEleccionPersonalActionPerformed

    private void btnEleccionAgenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEleccionAgenciaActionPerformed
        // TODO add your handling code here:
        Cliente cliente = new AgenciaDeViajes();
     
        frmAgenciaDeViajes agenciaFrame = new frmAgenciaDeViajes(cliente);
        agenciaFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnEleccionAgenciaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmTipoDeReservación.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmTipoDeReservación.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmTipoDeReservación.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmTipoDeReservación.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmTipoDeReservación().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEleccionAgencia;
    private javax.swing.JButton btnEleccionPersonal;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
