/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Dominio.AgenciaDeViajes;
import Dominio.Cliente;
import Dominio.Persona;

/**
 * Clase que representa el formulario 'frmTipoDeReservación1'. Este formulario
 * se utiliza para permitir al usuario elegir entre hacer una reservación como
 * cliente personal o como cliente de una agencia de viajes.
 */
public class frmTipoDeReservación1 extends javax.swing.JFrame {

    /**
     * Constructor de la clase 'frmTipoDeReservación1'. Inicializa y muestra los
     * componentes gráficos del formulario.
     */
    public frmTipoDeReservación1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnEleccionPersonal = new javax.swing.JButton();
        btnEleccionAgencia = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEleccionPersonal.setContentAreaFilled(false);
        btnEleccionPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEleccionPersonalActionPerformed(evt);
            }
        });
        jPanel1.add(btnEleccionPersonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 180, 70));

        btnEleccionAgencia.setContentAreaFilled(false);
        btnEleccionAgencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEleccionAgenciaActionPerformed(evt);
            }
        });
        jPanel1.add(btnEleccionAgencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 230, 190, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pantallaMedioDeReservacion.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
 /**
     * Maneja el evento de clic en el botón "btnEleccionPersonal". Abre el
     * formulario de registro para cliente personal.
     *
     * @param evt Evento de acción.
     */
    private void btnEleccionPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEleccionPersonalActionPerformed
        // TODO add your handling code here:
        Cliente cliente = new Persona();

        frmPersona1 personaFrame = new frmPersona1(cliente);
        personaFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnEleccionPersonalActionPerformed
    /**
     * Maneja el evento de clic en el botón "btnEleccionAgencia". Abre el
     * formulario de registro para cliente de agencia de viajes.
     *
     * @param evt Evento de acción.
     */
    private void btnEleccionAgenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEleccionAgenciaActionPerformed
        // TODO add your handling code here:
        Cliente cliente = new AgenciaDeViajes();

        frmAgenciaDeViajes1 agenciaFrame = new frmAgenciaDeViajes1(cliente);
        agenciaFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnEleccionAgenciaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmTipoDeReservación1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmTipoDeReservación1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmTipoDeReservación1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmTipoDeReservación1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmTipoDeReservación1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEleccionAgencia;
    private javax.swing.JButton btnEleccionPersonal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
